### ISSUE TITLE
append from folder redy for test

### ISSUE THREAD

**Issue by niewinny** [mx1001/HOps#15]
oh god that took a while...
anyway here it is 

so all can be appended form the file now, It took me few hours to figure out parenting stuff... so it works differently, now parent but also selection !!! is done in folder when You save. 

So it works like that, 
add 3 files to sub folder 
name them correctly 
parent 
add all stuff You want to like material modifiers and so on
select them correctly (that is only 1 object  selected  plane other to without selection)
group those 3 (name it same as object)

location ins important 
and before save all files needs to be visible and all planes selected (use outliner for that)

I did only 1 file as test (the triangle one)
rest has to be added like in here 1b599c3223786f6f3f631c5e77473a495ef7aa81
or just look in to the file (2nd one was modified)

lets keep it as separate branch for now, 

So the first task is to check if my relative path works correctly(just add in that triangle thing)
and then all other assets needs to be added to the sub.blend

**Comment by mx1001** [comment]
awesome! So they have to be 3 separate .blend files per brush?

**Comment by niewinny** [comment]
its not relevant anymore,closing
