### ISSUE TITLE
Our insert brushes duplicate materials to infinity

### ISSUE THREAD

**Issue by niewinny** [mx1001/HOps#17]
That is quite a big problem. whenever You add new insert brush new materials are created. After 20 its a total mess. So each insert brush has it's own materials, with textures that will increase rendering time horribly. 

I was thinking about moving them to link instead off append. that way materials will be linked as well(once). And then make a change to merge to unlink it first. But that may produce problems for upcoming asset lib which is working with or merge now.

Anyway we have to do something with it. Maybe it will be better to not add matterials to insert objects. That will fix the problem.

**Comment by mx1001** [comment]
i know im still looking into this. Maybe we might get a material consolidation script but I am not sure yet. I need the material separation or at least vertex groups.

**Comment by mx1001** [comment]
i think for the final release it'll have no materials on the subsets. Might keep it simple
may replace with materials called A B C and D just basic stuff.

**Comment by niewinny** [comment]
this is still a problem right ?

**Comment by mx1001** [comment]
we now have the material link that will merge materials of the same name. You can use it lazily too so you can select all and just use it under operations and thats that.
