### ISSUE TITLE
Sstep is not Sstepping correctly.

### ISSUE THREAD

**Issue by mx1001** [mx1001/HOps#48]
Currently we're discussing ways to consolidate the steps but currently sstep isnt working in the new setup. 

http://i.imgur.com/kh6IqY7.gifv

It actually isnt even applying the boolean modifier either. So thats problematic.
http://i.imgur.com/gTWxe4p.gifv
It applied the boolean the 2nd time. Which is strange. I wrote the code for the new one so these things tend to happen haha.

**Comment by niewinny** [comment]
behavior is fixed now 

we still need to do drawing stuff

**Comment by niewinny** [comment]
so set up the Draw function since currently it draws csharpen stats, and reaasign me to that
