### ISSUE TITLE
Cstep still isnt stepping right

### ISSUE THREAD

**Issue by mx1001** [mx1001/HOps#58]
This mesh was cstepped then sstepped and the bevels continue to modify the old area.
http://i.imgur.com/w91HTIr.gifv

If we look at it edit mode. 
http://i.imgur.com/vl7UldG.gifv

Now the cstep is working. Strange. Lets try that again. Maybe it isnt an issue
http://i.imgur.com/TR4S56c.gifv

I will continue checking it but for a moment it appeared to be the case.

**Comment by niewinny** [comment]
If you ever find a problem with beveling check bevel mod name first. We may have problem with modal bevel actually, I still need to resplit those, will look at it closely.
