### ISSUE TITLE
Crashing On Random

### ISSUE THREAD

**Issue by mx1001** [mx1001/HOps#66]
So I was using Hops with the CMD and i am receiving some errors at random. This was the first one that came up with subsets being inserted. A Non adjustable one too.

http://i.imgur.com/PdReAlq.png

These seem to happen at random but are currently a large issue since more than 10 minutes in blender will result in a crash.

So I tried it again and it crashed while inserting again. 

http://i.imgur.com/5tr3Pjz.png

Its beginning to look like a exception related issue. 

Lets try again. 
http://i.imgur.com/K7lcMKA.png

So it always ends with this exception_access_ violation. This is something we're seeing more of so it may be a blender change.

**Comment by JacquesLucke** [comment]
oops, Looks like it was my fault.. I'll fix it later today...

**Comment by mx1001** [comment]
yay. I felt like a complainer writing all of that haha.
