### ISSUE TITLE
Bmesh with Non BMesh Builds. 

### ISSUE THREAD

**Issue by mx1001** [mx1001/HOps#67]
When I merge using blender steam I get this error since the bmesh boolean isnt there. 

http://i.imgur.com/ao9aMlw.png

I guess this preps us for 2.77 but only if they add the bmesh option/

**Comment by niewinny** [comment]
it was done by booltool

there is an dev info that bmesh will not be in 2.77 and it will be back to daily build after release, 

it is not default behavior for csplit nor for booltool now so it shouldn't be a problem any longer.
still using csplit and sstep without it will produce topology problems

not much more that we can do anyway, hopefully it will be back in for 2.78
